export const tokens = {
  color: {
    primary: 'var(--color-primary)',
    secondary: 'var(--color-secondary)',
    surface: 'var(--color-surface)',
    onSurface: 'var(--color-on-surface)',
    error: 'var(--color-error)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    neutral: {
      50: 'var(--color-neutral-50)',
      100: 'var(--color-neutral-100)',
      200: 'var(--color-neutral-200)',
      300: 'var(--color-neutral-300)',
      400: 'var(--color-neutral-400)',
      500: 'var(--color-neutral-500)',
      600: 'var(--color-neutral-600)',
      700: 'var(--color-neutral-700)',
      800: 'var(--color-neutral-800)',
      900: 'var(--color-neutral-900)',
    },
  },
  typography: {
    fontSize: {
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      md: 'var(--font-size-md)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
    },
    fontWeight: {
      regular: 'var(--font-weight-regular)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
    },
    lineHeight: {
      tight: 'var(--line-height-tight)',
      base: 'var(--line-height-base)',
      loose: 'var(--line-height-loose)',
    },
    fontFamily: {
      heading: 'var(--font-family-heading)',
      body: 'var(--font-family-body)',
      mono: 'var(--font-family-mono)',
    },
  },
  spacing: {
    1: 'var(--space-1)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
    10: 'var(--space-10)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
  },
  radius: {
    none: 'var(--radius-none)',
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    full: 'var(--radius-full)',
  },
  shadow: {
    none: 'var(--shadow-none)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    overlay: 'var(--shadow-overlay)',
  },
  motion: {
    duration: {
      fast: 'var(--duration-fast)',
      base: 'var(--duration-base)',
      slow: 'var(--duration-slow)',
    },
    easing: {
      easeIn: 'var(--easing-ease-in)',
      easeOut: 'var(--easing-ease-out)',
      spring: 'var(--easing-spring)',
    },
  },
  breakpoints: {
    xs: 'var(--bp-xs)',
    sm: 'var(--bp-sm)',
    md: 'var(--bp-md)',
    lg: 'var(--bp-lg)',
    xl: 'var(--bp-xl)',
    '2xl': 'var(--bp-2xl)',
  },
};
